### ISSUE TITLE
Maximum QTS Version

### ISSUE THREAD

**Issue by Flyingfufu** [OneCDOnly/SortMyQPKGs#19]
Hello,

First of all, many thanks for your very nice package.

Looking to upgrade it to the latest version this morning, the install is failing. Looking a bit deeper, I figured out that the max QTS version allowed is QTS_MAX_VERSION="5.1.8", while I'm already on 5.2.0.

Any chance to update the qpkg.cfg file and get a new qpkg file ?

**Comment by OneCDOnly** [comment]
Hi @Flyingfufu 🤓 

Due to changes in QTS 5.2.0, SortMyQPKGs is no-longer effective. QTS 5.2.0 now attempts to start many QPKGs at the same time, and does so non-sequentially. 

QPKGs must now ensure the `Dependency` key is set (by the package maintainer) so QTS can build a dependency tree and start QPKGs accordingly. More information here: https://forum.qnap.com/viewtopic.php?p=867137#p867137
